# Generated by Django 5.1.7 on 2025-03-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSummary',
            fields=[
                ('match_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('margin', models.CharField(blank=True, max_length=50, null=True)),
                ('match_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=100)),
                ('batting_style', models.CharField(max_length=50)),
                ('bowling_style', models.CharField(max_length=50)),
                ('playing_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowling_team', models.CharField(max_length=100)),
                ('overs', models.FloatField()),
                ('maiden', models.IntegerField()),
                ('runs_conceded', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('economy', models.FloatField()),
                ('dot_balls', models.IntegerField()),
                ('fours_conceded', models.IntegerField()),
                ('sixes_conceded', models.IntegerField()),
                ('wides', models.IntegerField()),
                ('no_balls', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_summaries', to='api01.matchsummary')),
                ('bowler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_records', to='api01.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_innings', models.CharField(max_length=100)),
                ('batting_pos', models.IntegerField()),
                ('out_or_not_out', models.CharField(max_length=10)),
                ('runs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('strike_rate', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_summaries', to='api01.matchsummary')),
                ('batsman_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_records', to='api01.player')),
            ],
        ),
    ]
