# Generated by Django 5.1.7 on 2025-03-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingsummary',
            name='strike_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
